In [2]:
import numpy as np 
salaries = np.genfromtxt('salary.csv',delimiter = ',')
salaries

array([60000., 58000., 56967., ..., 54647., 25000., 70000.])

In [3]:
salaries.shape

(1147,)

In [4]:
mean = np.mean(salaries)
mean

55894.53879686138

In [5]:
median = np.median(salaries)
median

48000.0

In [6]:
print(median)

48000.0


In [7]:
std_dev = np.std(salaries)
std_dev

55170.37550939316

In [8]:
var = np.var(salaries)
var

3043770333.8474483

In [11]:
# indexing and slicing of numpy arrays 

a = np.arange(11)**2 # square 
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [12]:
a = np.arange(11)**3 # cube 
a

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [13]:
a[2]

8

In [14]:
a[-2]

729

In [15]:
a[0:5]

array([ 0,  1,  8, 27, 64], dtype=int32)

In [16]:
a[2:-2]

array([  8,  27,  64, 125, 216, 343, 512], dtype=int32)

In [17]:
a[::-1]

array([1000,  729,  512,  343,  216,  125,   64,   27,    8,    1,    0],
      dtype=int32)

In [22]:
# numpy advance features 

students = np.array([['Shweta','Sneha','Nil'],[10,20,30],[20,30,40]])
students

array([['Shweta', 'Sneha', 'Nil'],
       ['10', '20', '30'],
       ['20', '30', '40']], dtype='<U6')

In [21]:
students.shape

(3, 3)

In [23]:
students[0]

array(['Shweta', 'Sneha', 'Nil'], dtype='<U6')

In [24]:
students[1]

array(['10', '20', '30'], dtype='<U6')

In [25]:
students[2]

array(['20', '30', '40'], dtype='<U6')

In [26]:
students[0,1]

'Sneha'

In [27]:
students[1,1]

'20'

In [28]:
students [1][1]

'20'