In [1]:
import numpy as np

In [2]:
array_nd = np.arange(6)

In [3]:
array_nd

array([0, 1, 2, 3, 4, 5])

In [6]:
array_nd.shape

(6,)

In [11]:
array_nd = np.arange(6).reshape(2,3)

In [12]:
array_nd

array([[0, 1, 2],
       [3, 4, 5]])

In [10]:
array_nd

array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
array_ones = np.ones_like(array_nd)

In [15]:
array_ones

array([[1, 1, 1],
       [1, 1, 1]])

In [18]:
# basic numpy operations 

a = np.array([10,20,30])
b = np.array([30,20,10])
a+b

array([40, 40, 40])

In [19]:
a-b

array([-20,   0,  20])

In [20]:
a*b

array([300, 400, 300])

In [21]:
a/b

array([0.33333333, 1.        , 3.        ])

In [22]:
# comparison operators 

a<20

array([ True, False, False])

In [23]:
a>1111

array([False, False, False])

In [33]:
# universal functions in numpy 

angles_in_degrees = np.array([0,30,45,60,90])

# angles_in_radians = angles_in_degrees*(np.pi/180)

angles_in_radians = np.radians(angles_in_degrees)

In [34]:
angles_in_radians

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [28]:
# printing arrays 

array = np.arange(12).reshape(4,3)

In [29]:
array

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [30]:
print(array)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
